databases:
  - name: footwear_prod_db
    databaseName: footwear_db
    user: footwear
    plan: free

services:
  - type: web
    name: footwear_rails_app
    runtime: ruby
    # plan: free
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "bundle install" # preDeployCommand only available on paid instance types
    preDeployCommand: "bundle exec rails db:migrate"
    preDeployCommand: "bundle exec rails test:all"
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: footwear_prod_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default