databases:
  - name: footwear_prod_db
    databaseName: footwear_prod_db
    region: ohio
    user: footwear
    plan: free

services:
  - type: web
    name: footwear_prod_rails_app
    runtime: ruby
    region: ohio
    buildCommand: "./bin/render-build.sh"
    preDeployCommand: "./bin/render-pre-deploy.sh" # preDeployCommand only available on paid instance types
    startCommand: "bundle exec rails server"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: footwear_prod_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
      - key: WEB_CONCURRENCY
        value: 2 # sensible default