toolbar:
  - undo redo | blocks | bold italic | table | alignleft aligncenter alignright | bullist numlist outdent indent | removeformat
  - image | link
plugins:
  - image
  - link
  - table
block_formats: 'Paragraph=p; Header 2=h2; Header 3=h3; Header 4=h4; Header 5=h5; Header 6=h6'